# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the Node.js image with the required version for the project
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package files to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy all files to the working directory
COPY . .

# Build the TypeScript files
RUN npm run build

# Create the final release image
FROM node:18-alpine AS release

# Set working directory
WORKDIR /app

# Copy built files and necessary package information
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package-lock.json /app/node_modules ./ 

# Environment configuration for runtime (configured externally)
ENV REST_BASE_URL=""
ENV AUTH_BASIC_USERNAME=""
ENV AUTH_BASIC_PASSWORD=""
ENV AUTH_BEARER=""
ENV AUTH_APIKEY_HEADER_NAME=""
ENV AUTH_APIKEY_VALUE=""
ENV REST_ENABLE_SSL_VERIFY="true"
ENV REST_RESPONSE_SIZE_LIMIT="10000"

# Command to run the server
ENTRYPOINT ["node", "build/index.js"]